# Generated by Django 4.2.21 on 2025-05-09 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_user", common.models.fields.TextField()),
                ("db_schema", common.models.fields.TextField()),
                ("db_table", common.models.fields.TextField()),
                (
                    "action",
                    common.models.fields.TextField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                        ]
                    ),
                ),
                ("model_id", common.models.fields.PositiveBigIntegerField()),
                ("old_data", common.models.fields.JSONField(null=True)),
                ("new_data", common.models.fields.JSONField(null=True)),
                ("created_at", common.models.fields.DateTimeField()),
            ],
            options={
                "verbose_name": "Registro de acción",
                "verbose_name_plural": "Registro de acciones",
                "permissions": [("view_action_log", "Ver registro de acciones")],
            },
        ),
        migrations.CreateModel(
            name="ActionLogHistorical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_user", common.models.fields.TextField()),
                ("db_schema", common.models.fields.TextField()),
                ("db_table", common.models.fields.TextField()),
                (
                    "action",
                    common.models.fields.TextField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                        ]
                    ),
                ),
                ("model_id", common.models.fields.PositiveBigIntegerField()),
                ("old_data", common.models.fields.JSONField(null=True)),
                ("new_data", common.models.fields.JSONField(null=True)),
                ("created_at", common.models.fields.DateTimeField()),
            ],
            options={
                "verbose_name": "Registro histórico de acción",
                "verbose_name_plural": "Registro histórico de acciones",
                "permissions": [
                    ("view_action_log_historical", "Ver registro histórico de acciones")
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLogHistorical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_ip", common.models.fields.CharField(max_length=20)),
                ("url", common.models.fields.TextField(blank=True)),
                ("method", common.models.fields.CharField(max_length=10)),
                ("response_code", common.models.fields.PositiveSmallIntegerField()),
                ("execution_time_ms", common.models.fields.IntegerField()),
                ("created_at", common.models.fields.DateTimeField()),
                (
                    "user",
                    common.models.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro histórico de petición",
                "verbose_name_plural": "Registro histórico de peticiones",
                "permissions": [
                    (
                        "view_request_log_historical",
                        "Ver registro histórico de peticiones",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_ip", common.models.fields.CharField(max_length=20)),
                ("url", common.models.fields.TextField(blank=True)),
                ("method", common.models.fields.CharField(max_length=10)),
                ("response_code", common.models.fields.PositiveSmallIntegerField()),
                ("execution_time_ms", common.models.fields.IntegerField()),
                ("created_at", common.models.fields.DateTimeField()),
                (
                    "user",
                    common.models.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de petición",
                "verbose_name_plural": "Registro de peticiones",
                "permissions": [("view_request_log", "Ver registro de peticiones")],
            },
        ),
    ]
