# Generated by Django 4.2.21 on 2025-05-14 20:41

import django.contrib.postgres.functions
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="created_at",
            field=common.models.fields.DateTimeField(
                default=django.contrib.postgres.functions.TransactionNow()
            ),
        ),
        migrations.AlterField(
            model_name="actionloghistorical",
            name="created_at",
            field=common.models.fields.DateTimeField(
                default=django.contrib.postgres.functions.TransactionNow()
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="created_at",
            field=common.models.fields.DateTimeField(
                default=django.contrib.postgres.functions.TransactionNow()
            ),
        ),
        migrations.AlterField(
            model_name="requestloghistorical",
            name="created_at",
            field=common.models.fields.DateTimeField(
                default=django.contrib.postgres.functions.TransactionNow()
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=common.models.fields.DateTimeField(
                default=django.contrib.postgres.functions.TransactionNow(),
                verbose_name="Creado",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=common.models.fields.DateTimeField(
                default=django.contrib.postgres.functions.TransactionNow(),
                verbose_name="Actualizado",
            ),
        ),
    ]
